name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Deploy to environment'
        required: true
        options:
          - dev
          - qa
          - prod
          - stage
        default: 'dev'

permissions:
  deployments: write  
  id-token: write
  contents: write
  actions: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Deployment
        uses: chrnorm/deployment-action@v2
        id: create_deployment
        with:
          environment: ${{ github.event.inputs.environment }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'success'
          deployment-id: ${{ steps.create_deployment.outputs.deployment_id }}
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'failure'
          deployment-id: ${{ steps.create_deployment.outputs.deployment_id }} 
      